### ISSUE TITLE
MSN PRODUCTION

### ISSUE THREAD

**Issue by berthutapea** [berthutapea/msnproduction.com#1]
![img-1](https://github.com/berthutapea/msnproduction.com/assets/111676859/99fbd0c0-1f92-4bb7-9802-367e997ee2c3)
![img-2](https://github.com/berthutapea/msnproduction.com/assets/111676859/28601988-b305-47c4-a2d3-6de2f590bf07)
![img-3](https://github.com/berthutapea/msnproduction.com/assets/111676859/e642ebeb-6090-4825-af78-0ca62ae2482e)
![img-4](https://github.com/berthutapea/msnproduction.com/assets/111676859/7e3ef8cf-6127-41be-86de-66f465d6dc3d)
![img-5](https://github.com/berthutapea/msnproduction.com/assets/111676859/e1301e3f-0dbb-44c6-a0b6-d973087f6140)

**Comment by berthutapea** [comment]
![MSN-PRODUCTION-LOGO](https://user-images.githubusercontent.com/111676859/230091561-cbb6e02f-387d-46dc-a3fa-ea789047550d.png)

**Comment by haqimkq** [comment]
Saya belum berhasil instal mas, keterangan minta npm audit

**Comment by haqimkq** [comment]
sudah saya coba di local maupun di hosting sama saja

**Comment by haqimkq** [comment]
kalau di hosting ada ga step by stepnya bang
